export const SET_IS_ROOM_HOST = "SET_IS_ROOM_HOST";
export const SET_CONNECT_ONLY_WITH_AUDIO = "SET_CONNECT_ONLY_WITH_AUDIO";
export const SET_ROOM_ID = "SET_ROOM_ID";
export const SET_IDENTITY = "SET_IDENTITY";
export const SET_SHOW_OVERLAY = "SET_SHOW_OVERLAY";
export const SET_PARTICIPANTS = "SET_PARTICIPANTS";
